import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const colleges = [
  {
    name: "Indian Institute of Technology Bombay",
    location: "Mumbai",
    state: "Maharashtra",
    fees: 250000,
    rating: 4.9,
    courses: ["Computer Science", "Electrical Engineering", "Mechanical Engineering", "Chemical Engineering"],
    placementPercentage: 98,
    avgPackage: 22.5,
    description: "IIT Bombay is a premier engineering institute known for its academic excellence and research.",
    examCutoffRank: 100,
    examType: "JEE_ADVANCED",
    type: "IIT",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/2e/IITBMainBuildingCROP.jpg",
    admissionUrl: "https://www.iitb.ac.in/newacadhome/btech.jsp"
  },
  {
    name: "Indian Institute of Technology Delhi",
    location: "New Delhi",
    state: "Delhi",
    fees: 240000,
    rating: 4.9,
    courses: ["Computer Science", "Electrical Engineering", "Mechanical Engineering", "Civil Engineering"],
    placementPercentage: 97,
    avgPackage: 21.0,
    description: "IIT Delhi is a leading technical university located in the heart of the capital.",
    examCutoffRank: 150,
    examType: "JEE_ADVANCED",
    type: "IIT",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/IIT_Delhi_Main_Building.jpeg/960px-IIT_Delhi_Main_Building.jpeg",
    admissionUrl: "https://home.iitd.ac.in/admissions.php"
  },
  {
    name: "Indian Institute of Technology Madras",
    location: "Chennai",
    state: "Tamil Nadu",
    fees: 230000,
    rating: 4.9,
    courses: ["Computer Science", "Electrical Engineering", "Mechanical Engineering", "Aerospace Engineering"],
    placementPercentage: 97,
    avgPackage: 20.5,
    description: "IIT Madras is consistently ranked as the top engineering institute in India.",
    examCutoffRank: 200,
    examType: "JEE_ADVANCED",
    type: "IIT",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/IIT_Madras_campus_main_gate.jpg/960px-IIT_Madras_campus_main_gate.jpg",
    admissionUrl: "https://admissions.iitm.ac.in/"
  },
  {
    name: "Indian Institute of Technology Kanpur",
    location: "Kanpur",
    state: "Uttar Pradesh",
    fees: 225000,
    rating: 4.8,
    courses: ["Computer Science", "Electrical Engineering", "Mechanical Engineering", "Materials Science"],
    placementPercentage: 95,
    avgPackage: 19.0,
    description: "IIT Kanpur is renowned for its strong focus on research and academic rigor.",
    examCutoffRank: 350,
    examType: "JEE_ADVANCED",
    type: "IIT",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Samtel_Research_and_Development_Building%2C_at_IIT_Kanpur.jpg/960px-Samtel_Research_and_Development_Building%2C_at_IIT_Kanpur.jpg",
    admissionUrl: "https://www.iitk.ac.in/new/admissions"
  },
  {
    name: "Indian Institute of Technology Kharagpur",
    location: "Kharagpur",
    state: "West Bengal",
    fees: 220000,
    rating: 4.8,
    courses: ["Computer Science", "Electrical Engineering", "Mechanical Engineering", "Ocean Engineering"],
    placementPercentage: 94,
    avgPackage: 18.5,
    description: "The first IIT established in India, Kharagpur has a massive campus and diverse courses.",
    examCutoffRank: 500,
    examType: "JEE_ADVANCED",
    type: "IIT",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Bubai_Manna_%28IIT_Kharagpur_main_building%29.jpg/960px-Bubai_Manna_%28IIT_Kharagpur_main_building%29.jpg",
    admissionUrl: "http://www.iitkgp.ac.in/admissions"
  },
  {
    name: "Indian Institute of Technology Roorkee",
    location: "Roorkee",
    state: "Uttarakhand",
    fees: 215000,
    rating: 4.7,
    courses: ["Computer Science", "Electrical Engineering", "Mechanical Engineering", "Civil Engineering"],
    placementPercentage: 93,
    avgPackage: 17.5,
    description: "IIT Roorkee has a rich heritage and is one of the oldest technical institutions in Asia.",
    examCutoffRank: 700,
    examType: "JEE_ADVANCED",
    type: "IIT",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e0/IIT_Roorkee_Main_Building.jpg",
    admissionUrl: "https://iitr.ac.in/Admissions/index.html"
  },
  {
    name: "Indian Institute of Technology Guwahati",
    location: "Guwahati",
    state: "Assam",
    fees: 210000,
    rating: 4.7,
    courses: ["Computer Science", "Electrical Engineering", "Mechanical Engineering", "Biotechnology"],
    placementPercentage: 92,
    avgPackage: 16.5,
    description: "IIT Guwahati is known for its beautiful campus on the banks of the Brahmaputra.",
    examCutoffRank: 900,
    examType: "JEE_ADVANCED",
    type: "IIT",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e9/IIT_Guwahati_across_the_lake.jpg",
    admissionUrl: "https://iitg.ac.in/acad/admissions/"
  },
  {
    name: "Indian Institute of Technology Hyderabad",
    location: "Hyderabad",
    state: "Telangana",
    fees: 200000,
    rating: 4.6,
    courses: ["Computer Science", "Electrical Engineering", "AI & Data Science"],
    placementPercentage: 91,
    avgPackage: 15.5,
    description: "IIT Hyderabad is a top second-generation IIT with strong industry ties.",
    examCutoffRank: 1200,
    examType: "JEE_ADVANCED",
    type: "IIT",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/14/Iit_hyderabad-3.jpg",
    admissionUrl: "https://iith.ac.in/admissions/"
  },
  {
    name: "National Institute of Technology Tiruchirappalli",
    location: "Trichy",
    state: "Tamil Nadu",
    fees: 150000,
    rating: 4.5,
    courses: ["Computer Science", "Electronics", "Mechanical", "Civil"],
    placementPercentage: 92,
    avgPackage: 12.5,
    description: "NIT Trichy is the top-ranked NIT in India, offering excellent placements.",
    examCutoffRank: 3000,
    examType: "JEE_MAIN",
    type: "NIT",
    imageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?q=80&w=960&auto=format&fit=crop",
    admissionUrl: "https://www.nitt.edu/home/admissions/"
  },
  {
    name: "National Institute of Technology Karnataka",
    location: "Surathkal",
    state: "Karnataka",
    fees: 145000,
    rating: 4.5,
    courses: ["Computer Science", "IT", "Electrical", "Mechanical"],
    placementPercentage: 90,
    avgPackage: 11.5,
    description: "NIT Surathkal is famous for its private beach and stellar academic record.",
    examCutoffRank: 4000,
    examType: "JEE_MAIN",
    type: "NIT",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/NITK_surathkal.jpg/960px-NITK_surathkal.jpg",
    admissionUrl: "https://www.nitk.ac.in/admissions"
  },
  {
    name: "National Institute of Technology Warangal",
    location: "Warangal",
    state: "Telangana",
    fees: 140000,
    rating: 4.4,
    courses: ["Computer Science", "Electronics", "Chemical", "Civil"],
    placementPercentage: 88,
    avgPackage: 10.5,
    description: "NIT Warangal is one of the oldest and most prestigious RECs/NITs.",
    examCutoffRank: 5000,
    examType: "JEE_MAIN",
    type: "NIT",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b7/Nitw_gate_hindi.jpg",
    admissionUrl: "https://nitw.ac.in/admissions"
  },
  {
    name: "National Institute of Technology Calicut",
    location: "Calicut",
    state: "Kerala",
    fees: 135000,
    rating: 4.3,
    courses: ["Computer Science", "Electrical", "Mechanical", "Architecture"],
    placementPercentage: 86,
    avgPackage: 9.5,
    description: "NIT Calicut offers a great blend of academics and natural beauty.",
    examCutoffRank: 7000,
    examType: "JEE_MAIN",
    type: "NIT",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/NIT_CALICUT.jpg/960px-NIT_CALICUT.jpg",
    admissionUrl: "https://nitc.ac.in/admissions"
  },
  {
    name: "National Institute of Technology Rourkela",
    location: "Rourkela",
    state: "Odisha",
    fees: 130000,
    rating: 4.3,
    courses: ["Computer Science", "Electronics", "Mining", "Mechanical"],
    placementPercentage: 85,
    avgPackage: 9.0,
    description: "NIT Rourkela has one of the largest campuses and diverse engineering departments.",
    examCutoffRank: 8000,
    examType: "JEE_MAIN",
    type: "NIT",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/NITMainGate.jpg/960px-NITMainGate.jpg",
    admissionUrl: "https://nitrkl.ac.in/Academics/Admissions/"
  },
  {
    name: "Birla Institute of Technology and Science Pilani",
    location: "Pilani",
    state: "Rajasthan",
    fees: 550000,
    rating: 4.8,
    courses: ["Computer Science", "Electrical", "Mechanical", "Chemical"],
    placementPercentage: 96,
    avgPackage: 18.0,
    description: "BITS Pilani is the best private engineering institute in India with a unique zero-attendance policy.",
    examCutoffRank: 320,
    examType: "BITSAT",
    type: "Private",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/ff/BITS-Pilani_campus_aerial_view.jpg",
    admissionUrl: "https://www.bitsadmission.com/"
  },
  {
    name: "IIIT Hyderabad",
    location: "Hyderabad",
    state: "Telangana",
    fees: 350000,
    rating: 4.7,
    courses: ["Computer Science", "Electronics & Communication"],
    placementPercentage: 98,
    avgPackage: 20.0,
    description: "IIIT Hyderabad is a research-focused institute with unmatched CS placements.",
    examCutoffRank: 1500,
    examType: "JEE_MAIN",
    type: "IIIT",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/IIIT_Hyderabad_campus_in_Hyderabad_34.jpg/960px-IIIT_Hyderabad_campus_in_Hyderabad_34.jpg",
    admissionUrl: "https://ugadmissions.iiit.ac.in/"
  },
  {
    name: "IIIT Bangalore",
    location: "Bangalore",
    state: "Karnataka",
    fees: 380000,
    rating: 4.6,
    courses: ["Computer Science", "IT", "Data Science"],
    placementPercentage: 95,
    avgPackage: 19.0,
    description: "Located in the tech hub of India, IIIT Bangalore offers great industry exposure.",
    examCutoffRank: 4000,
    examType: "JEE_MAIN",
    type: "IIIT",
    imageUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?q=80&w=960&auto=format&fit=crop",
    admissionUrl: "https://www.iiitb.ac.in/admissions"
  },
  {
    name: "Vellore Institute of Technology",
    location: "Vellore",
    state: "Tamil Nadu",
    fees: 195000,
    rating: 4.2,
    courses: ["Computer Science", "Electronics", "IT", "Biotechnology"],
    placementPercentage: 85,
    avgPackage: 8.5,
    description: "VIT Vellore is one of the most popular private universities with a massive student intake.",
    examCutoffRank: 15000,
    examType: "VITEEE",
    type: "Private",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/43/Technology_Tower%28VIT%29.jpg",
    admissionUrl: "https://viteee.vit.ac.in/"
  },
  {
    name: "Delhi Technological University",
    location: "New Delhi",
    state: "Delhi",
    fees: 190000,
    rating: 4.4,
    courses: ["Computer Science", "Software Engineering", "Mechanical", "Electrical"],
    placementPercentage: 90,
    avgPackage: 13.5,
    description: "Formerly Delhi College of Engineering, DTU is known for its coding culture.",
    examCutoffRank: 10000,
    examType: "JEE_MAIN",
    type: "State",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d5/DelhiCollegeOfEngineering_BawanaCampus.jpg",
    admissionUrl: "https://dtu.ac.in/Web/admission/"
  },
  {
    name: "Netaji Subhas University of Technology",
    location: "New Delhi",
    state: "Delhi",
    fees: 185000,
    rating: 4.3,
    courses: ["Computer Science", "IT", "Electronics"],
    placementPercentage: 88,
    avgPackage: 12.5,
    description: "NSUT is a premier state university in Delhi with excellent placements.",
    examCutoffRank: 12000,
    examType: "JEE_MAIN",
    type: "State",
    imageUrl: "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?q=80&w=960&auto=format&fit=crop",
    admissionUrl: "https://nsut.ac.in/en/admissions"
  },
  {
    name: "College of Engineering Pune",
    location: "Pune",
    state: "Maharashtra",
    fees: 120000,
    rating: 4.2,
    courses: ["Computer Science", "Mechanical", "Electrical", "Civil"],
    placementPercentage: 85,
    avgPackage: 9.5,
    description: "One of the oldest engineering colleges in India with a strong heritage.",
    examCutoffRank: 15000,
    examType: "MHT_CET",
    type: "State",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Bust_of_Sir_Visvesvarayya_facing_the_College%27s_Main_building.jpg/960px-Bust_of_Sir_Visvesvarayya_facing_the_College%27s_Main_building.jpg",
    admissionUrl: "https://www.coep.org.in/admissions"
  },
  {
    name: "Jadavpur University",
    location: "Kolkata",
    state: "West Bengal",
    fees: 10000,
    rating: 4.5,
    courses: ["Computer Science", "IT", "Electrical", "Mechanical"],
    placementPercentage: 90,
    avgPackage: 12.0,
    description: "Famous for its extremely low fees and high placement ROI.",
    examCutoffRank: 200,
    examType: "WBJEE",
    type: "State",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Campus_Road_-_Jadavpur_University_-_Kolkata_2015-01-08_2394.JPG/960px-Campus_Road_-_Jadavpur_University_-_Kolkata_2015-01-08_2394.JPG",
    admissionUrl: "http://www.jaduniv.edu.in/admissions"
  },
  {
    name: "Manipal Institute of Technology",
    location: "Manipal",
    state: "Karnataka",
    fees: 450000,
    rating: 4.1,
    courses: ["Computer Science", "Aeronautical", "Automobile", "IT"],
    placementPercentage: 82,
    avgPackage: 8.0,
    description: "MIT Manipal offers a vibrant campus life and diverse engineering programs.",
    examCutoffRank: 25000,
    examType: "MET",
    type: "Private",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/MIT_Manipal_Campus.jpg/960px-MIT_Manipal_Campus.jpg",
    admissionUrl: "https://manipal.edu/mit/admissions.html"
  },
  {
    name: "SRM Institute of Science and Technology",
    location: "Chennai",
    state: "Tamil Nadu",
    fees: 250000,
    rating: 4.0,
    courses: ["Computer Science", "Aerospace", "Civil", "Electronics"],
    placementPercentage: 80,
    avgPackage: 6.5,
    description: "SRM is a large private university with strong international collaborations.",
    examCutoffRank: 30000,
    examType: "SRMJEEE",
    type: "Private",
    imageUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c8f1?q=80&w=960&auto=format&fit=crop",
    admissionUrl: "https://www.srmist.edu.in/admission-india/"
  },
  {
    name: "Thapar Institute of Engineering and Technology",
    location: "Patiala",
    state: "Punjab",
    fees: 380000,
    rating: 4.1,
    courses: ["Computer Science", "Electronics", "Mechanical"],
    placementPercentage: 83,
    avgPackage: 9.0,
    description: "Thapar is a leading private university in North India with a strong alumni network.",
    examCutoffRank: 40000,
    examType: "JEE_MAIN",
    type: "Deemed",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/29/Thapar_Campus_Aerial_View.jpg",
    admissionUrl: "https://www.thapar.edu/admissions"
  },
  {
    name: "Anna University",
    location: "Chennai",
    state: "Tamil Nadu",
    fees: 60000,
    rating: 4.3,
    courses: ["Computer Science", "Mechanical", "Electrical", "Printing Tech"],
    placementPercentage: 85,
    avgPackage: 8.0,
    description: "A major technical university in South India with numerous affiliated colleges.",
    examCutoffRank: 500,
    examType: "TNEA",
    type: "State",
    imageUrl: "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?q=80&w=960&auto=format&fit=crop",
    admissionUrl: "https://www.annauniv.edu/cfa/"
  }
];

async function main() {
  console.log("Start seeding...");
  // Clear existing data first
  await prisma.college.deleteMany();
  
  for (const c of colleges) {
    const college = await prisma.college.create({
      data: c,
    });
    console.log(`Created college with id: ${college.id}`);
  }
  console.log("Seeding finished.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
